name: C/C++ CI

on:
  push:
    branches: [ "REL8_0_STABLE" ]
  pull_request:
    branches: [ "REL8_0_STABLE" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
